# Generated by LangFlow
from typing import TypedDict, Annotated
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

class AgentState(TypedDict):
    query: string
    output: string

def input(state: AgentState) -> AgentState:
    # Input type: dialog
    # Input variable: query (string)
    return state
    return state

def llm_node(state: AgentState) -> AgentState:
    llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0.7)
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful assistant."),
        ("user", "{{query}}")
    ])
    chain = prompt | llm
    response = chain.invoke(state)
    state["output"] = response.content
    return state

def code_node(state: AgentState) -> AgentState:
    # 自定义代码执行
    result = state['output'].upper()
    state['output'] = result
    return state

def output(state: AgentState) -> AgentState:
    print("Output:", state["output"])
    return state


def build_graph():
    workflow = StateGraph(AgentState)

    workflow.add_node("input", input)
    workflow.add_node("llm_node", llm_node)
    workflow.add_node("code_node", code_node)
    workflow.add_node("output", output)

    workflow.set_entry_point("input")
    workflow.add_edge("input", "llm_node")
    workflow.add_edge("llm_node", "code_node")
    workflow.add_edge("code_node", "output")
    workflow.add_edge("output", END)

    return workflow.compile()


if __name__ == "__main__":
    app = build_graph()
    # Example usage
    # result = app.invoke({"query": "Hello"})
    # print(result)